routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::domain('promo.devrules.ru')->group(function () {
    Route::get('/', function (){
        return 'bla bla bla';
    });
});
Route::domain('devrules.ru')->group(function () {
    Route::view('/', 'frontend.index')->name('home');

    Route::post('sendMessageToTelegram', 'SendToTelegramController');

    Route::get('notes', 'NotesController@indexFront')->name('notes');
    Route::get('notes/{note}', 'NotesController@showFront')->name('note.page');

    Route::get('myportfolio', 'PortfolioController@indexFront')->name('portfolio.front');
    Route::get('myportfolio/{item}', 'PortfolioController@showFront')->name('portfolio.page');

    Route::get('projects', 'ProjectsController@indexFront')->name('projects');
    Route::get('projects/{project}', 'ProjectsController@showFront')->name('project.page');

    Route::resource('notez', 'NotesController')->middleware('role:admin');
    Route::post('notez/image', 'NotesController@imageTempStore')->name('notez.imageTempStore');
    Route::post('notez/imageSave', 'NotesController@imageStore')->name('notez.imageSave');

    Route::resource('portfolioz', 'PortfolioController')->middleware('role:admin');

    Route::resource('projectes', 'ProjectsController')->middleware('role:admin');

    Auth::routes();
});

app/Portfolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    public $fillable = [
        'name', 'tech', 'main_img', 'images', 'seo_desc', 'seo_key', 'text', 'slug',
    ];
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use App\Portfolio;
use Illuminate\Http\Request;

class PortfolioController extends Controller
{

    /**
     * Display a listing of the resource for frontend.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexFront()
    {
        return view('frontend.portfolio', [
            'portfolio' => Portfolio::orderBy('created_at', 'desc')->get()->take(24),
        ]);
    }

    public function showFront($id)
    {
        return view('frontend.page._portfolio_page', [
            'work' => Portfolio::find($id),
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Portfolio::orderBy('id', 'desc')->get();
        return view('control.portfolio._portfolio_list', [
            'items' => $items,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('control.portfolio._create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $images_array = [];

        for ($i=1; $i < 4; $i++) { 
            if(strlen($request->input($i.'-src')) > 100){
                $images_array[] = [
                    'capture' => $request->input($i.'-capture'),
                    'img_path' => $this->getImagePath($request->input($i.'-src')),
                ];
                // var_dump($images_array);die;
            }
        }

        // var_dump(\json_encode($images_array));die;
        if($request->file('main_img')->isValid()){
            // $path = $request->file('main_img')->store('portfolio');
            $path = 'portfolio/'.\Str::random(20).'.jpg';
            $img = \Image::make($request->file('main_img'))->save($path, 80, 'jpg');
        }
      
        Portfolio::create([
            'name' => $request->input('name'),
            'tech' => $request->input('tech'),
            'seo_desc' => $request->input('seo_desc'),
            'seo_key' => $request->input('seo_key'),
            'text' => $request->input('text'),
            'slug' => \Str::slug($request->input('name')),
            'main_img' => $path,
            'images' => json_encode($images_array),
        ]);

        return redirect()->route('portfolioz.index');
    }

    public function getImagePath($base64)
    {
        $data = explode(',', $base64);
        $path = 'portfolio/'.\Str::random(20).'.jpg';
        $img = \Image::make($data[1])->save($path, 80, 'jpg');

        return $path;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function show(Portfolio $portfolio)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // var_dump($portfolio->name);die;
        $item = Portfolio::find($id);
        return view('control.portfolio._update', [
            'item' => $item,
            'ref' => \Request::server('HTTP_REFERER'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // var_dump($request->hasFile('main_img'));die;
        if($request->hasFile('main_img')){
            if($request->file('main_img')->isValid()){
                // $path = $request->file('main_img')->store('portfolio');
                $path = 'portfolio/'.\Str::random(20).'.jpg';
                $img = \Image::make($request->file('main_img'))->save($path, 80, 'jpg');
                unlink($request->input('currentSrc'));
            }
        }else{
            $path = $request->input('currentSrc');
        }
      
        Portfolio::find($id)
            ->update([
                'name' => $request->input('name'),
                'tech' => $request->input('tech'),
                'seo_desc' => $request->input('seo_desc'),
                'seo_key' => $request->input('seo_key'),
                'text' => $request->input('text'),
                'slug' => \Str::slug($request->input('name')),
                'main_img' => $path,
                // 'images' => json_encode($images_array),
            ]);

        if(\Str::contains($request->input('refLink'), 'myportfolio/')){
            return redirect()->route('portfolio.page', \Str::afterLast($request->input('refLink'), '/'));
        }

        return redirect()->route('portfolioz.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $portfolio = Portfolio::find($id);

        if(file_exists($portfolio->main_img)) unlink($portfolio->main_img);
        
        foreach (json_decode($portfolio->images, true) as $value) {
            if(file_exists($value['img_path'])) unlink($value['img_path']);
        }

        $portfolio->delete();

        return redirect()->route('portfolioz.index');
        // var_dump('Есть');die;
    }
}

resources/views/control/portfolio/_create.blade.php
@extends('frontend.layouts.main')

@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.css">
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>
<span id="navFix" class="hidden"></span>
<!--Hero-->
<div class="pt-6 md:pt-32">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
      
    
        <div class="w-full leading-loose mb-3 flex justify-center">
            <form id="createPortForm" class="w-3/4 m-4 "  action="{{ route('portfolioz.store') }}" method="POST" enctype="multipart/form-data">
              {!! csrf_field() !!}
              <div class="w-full p-10 bg-white">
                <p class="text-gray-800 font-medium text-xl">Добавление работы:</p>
                <div class="flex mt-4 mb-3">
                  <button class="px-4 w-full hover:bg-blue-600 py-1 text-white font-light tracking-wider bg-blue-500 rounded" 
                          type="submit">Добавить</button>
                </div>               
                <div class="flex flex-no-wrap">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" title="Название" name="name" type="text" required="" placeholder="Название">
                </div>
                <div class="mt-2 flex flex-no-wrap items-center">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2" title="SEO Description" name="seo_desc" type="text" required="" placeholder="SEO Description">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" title="SEO Keywords" name="seo_key" type="text" required="" placeholder="SEO Keywords">
                </div>
                <div class="flex flex-no-wrap mt-3">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" title="Технологии" name="tech" type="text" required="" placeholder="Технологии">
                </div>

              </div>

              <div class="w-full p-10 bg-white mt-4">
                <div class="mt-2 flex flex-wrap items-center">
                  <div class="w-full">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 my-2" type="text" name="text" placeholder="Описание главного изображения">
                  </div>
                  <input type="file" class="bg-white text-black p-3 w-1/2" name="main_img" id="imgSrcUpload">      
                </div>
              </div>

              <div class="option-image-1 w-full px-10 py-4 bg-white mt-4">
                <div class="mt-2 w-full flex flex-wrap items-center text-black justify-center">
                  <input type="file" class="bg-white text-black p-3 w-1/3" name="1-image">
                  <input type="hidden" name="1-src"> 
                  <div class="hidden" id="1-full">
                    <div class="w-full">
                      <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 my-2" type="text" name="1-caption" placeholder="Описание изображения">
                    </div>
                    <div class="w-full 1-prev">
                       
                    </div>
                  </div>
                </div>
              </div>

              <div class="option-image-2 hidden w-full px-10 py-4 bg-white mt-4">
                <div class="mt-2 w-full flex flex-wrap items-center text-black justify-center">
                  <input type="file" class="bg-white text-black p-3 w-1/3" name="2-image"> 
                  <input type="hidden" name="2-src">
                  <div class="hidden" id="2-full">
                    <div class="w-full">
                      <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 my-2" type="text" name="2-caption" placeholder="Описание изображения">
                    </div>
                    <div class="w-full 2-prev">
                       
                    </div>
                  </div>
                </div>
              </div>

              <div class="option-image-3 hidden w-full px-10 py-4 bg-white mt-4">
                <div class="mt-2 w-full flex flex-wrap items-center text-black justify-center">
                  <input type="file" class="bg-white text-black p-3 w-1/3" name="3-image"> 
                  <input type="hidden" name="3-src"> 
                  <div class="hidden" id="3-full">
                    <div class="w-full">
                      <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 my-2" type="text" name="3-caption" placeholder="Описание изображения">
                    </div>
                    <div class="w-full 3-prev">
                       
                    </div>
                  </div>
                </div>
              </div>

              {{-- <div id="editor"></div> --}}
              
              
            </form>
          </div>

          


    </div>
</div>
@endsection
@section('js')
    
{{-- <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script> --}}
{{-- <script src="{{ asset('ckeditor/ckeditor.js') }}"></script> --}}
{{-- <script src="{{ asset('js/jq_tailwind_checkbox.js') }}"></script> --}}
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.js"></script> --}}


<script>

  window.onload = function () {
    // First event
    $('.option-image-1 input[name="1-image"]').on('change', function () {
      ajaxFunc(1);
      $('#1-full').removeClass('hidden'); //Show full info - image and input capture
      $('.option-image-2').removeClass('hidden'); //Show 2
      // Two event
      $('.option-image-2 input[name="2-image"]').on('change', function () {
        ajaxFunc(2);
        $('#2-full').removeClass('hidden'); //Show full info - image and input capture
        $('.option-image-3').removeClass('hidden'); //Show 2
        // Three event
        $('.option-image-3 input[name="3-image"]').on('change', function () {
          ajaxFunc(3);
          $('#3-full').removeClass('hidden'); //Show full info - image and input capture
        });
      });

    });

  }

  function ajaxFunc(number) {
    var file_data = $('input[name="'+number+'-image"]').prop('files')[0];
    var form_data = new FormData();
    form_data.append('file', file_data);
    $.ajax({
      type: "POST",
      url: "{{ route('notez.imageTempStore') }}",
      processData: false,
      cache: false,
      contentType: false,
      data: form_data,
      headers: {
          'X-CSRF-TOKEN': "{{ csrf_token() }}"
      },
      success: function (data) {
          // console.log('Ok');
          // console.log(data) 
          $('.'+number+'-prev').html(data['crop_block']);
          $('input[name="'+number+'-src"]').val(data['crop_base64']);         
      }
  });
  }
  // $('#imgSrcUpload').on('change', function () {
  //   var file_data = $('#imgSrcUpload').prop('files')[0];
  //   var form_data = new FormData();
  //   form_data.append('file', file_data);
  //         $.ajax({
  //           type: "POST",
  //           url: "{{ route('notez.imageTempStore') }}",
  //           processData: false,
  //           cache: false,
  //           contentType: false,
  //           data: form_data,
  //           headers: {
  //               'X-CSRF-TOKEN': "{{ csrf_token() }}"
  //           },
  //           success: function (data) {
  //               console.log(data);
  //               $('#originalImage').html(data['crop_block']);
  //               cropperInit();
  //           }
  //       });
  // });

  // function cropperInit(){
  //   const image = document.getElementById('image');
  //   const cropper = new Cropper(image, {
  //     aspectRatio: 16 / 9,
  //     scalable: false,
  //     zoomable: false,
  //   });

  //   $('#cutImage').on('click', function(){
  //     cropper.getCroppedCanvas({
  //       width: 1920,
  //       height: 1080,
  //       fillColor: '#fff',
  //       imageSmoothingEnabled: false,
  //       imageSmoothingQuality: 'medium',
  //     });
  //     cropper.getCroppedCanvas().toBlob((blob) => {
  //       const formData = new FormData();
  //     formData.append('file', blob);
  //     $.ajax({
  //           type: "POST",
  //           url: "{{ route('notez.imageTempStore') }}",
  //           processData: false,
  //           cache: false,
  //           contentType: false,
  //           data: formData,
  //           headers: {
  //               'X-CSRF-TOKEN': "{{ csrf_token() }}"
  //           },
  //           success: function (data) {
  //               console.log(data);
  //               $('#cropperImage').html(data['crop_block']);
  //               $('#src').val(data['crop_base64']);
  //           }
  //       });
  //     });
  //   });
  // }
</script>

<script>
  // import Cropper from 'cropperjs';

// const image = document.getElementById('image');
// const cropper = new Cropper(image, {
//   aspectRatio: 16 / 9,
//   crop(event) {
//     console.log(event.detail.x);
//     console.log(event.detail.y);
//     console.log(event.detail.width);
//     console.log(event.detail.height);
//     console.log(event.detail.rotate);
//     console.log(event.detail.scaleX);
//     console.log(event.detail.scaleY);
//   },
// });
</script>
@endsection

resources/views/control/portfolio/_portfolio_list.blade.php
@extends('frontend.layouts.main')

@section('content')
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>


<span id="navFix" class="hidden"></span>
<!--Hero-->
<div class="pt-6 md:pt-32 pb-8 h-full">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">

        <table class="border-collapse w-full mt-4">
            <thead>
                <tr>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Дата</th>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell w-3/5">Название</th>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($items as $item)
                <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                        {{\Carbon\Carbon::parse($item['created_at'])->format('d.m.Y')}}
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                        {{$item->name}}
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                        <form action="{{ route('portfolioz.destroy', $item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')       
                            <a href="{{route('portfolioz.edit', $item->id)}}" class="text-green-400 hover:text-blue-600 underline" title="Редактировать"><i class="far fa-edit"></i></a>
                            <button type="submit" class="text-red-400 hover:text-blue-600 underline pl-6" title="Удалить работу"><i class="far fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
                    
                @endforeach
                
            </tbody>
        </table>

    </div>
</div>

@endsection

resources/views/control/portfolio/_update.blade.php
@extends('frontend.layouts.main')

@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.css">
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>
<span id="navFix" class="hidden"></span>
<!--Hero-->
<div class="pt-6 md:pt-32">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
      
    
        <div class="w-full leading-loose mb-3 flex justify-center">
            <form id="createPortForm" class="w-3/4 m-4 "  action="{{ route('portfolioz.update', $item->id) }}" method="POST" enctype="multipart/form-data">
              {!! csrf_field() !!}
              @method('PUT')
              <input type="hidden" name="refLink" value="{{$ref}}">
              <div class="w-full p-10 bg-white">
                <p class="text-gray-800 font-medium text-xl">Редактирование работы:</p>
                <div class="flex mt-4 mb-3">
                  <button class="px-4 w-full hover:bg-blue-600 py-1 text-white font-light tracking-wider bg-blue-500 rounded" 
                          type="submit">Обновить</button>
                </div>               
                <div class="flex flex-no-wrap">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" value="{{$item->name}}" title="Название" name="name" type="text" required="" placeholder="Название">
                </div>
                <div class="mt-2 flex flex-no-wrap items-center">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2" value="{{$item->seo_desc}}" title="SEO Description" name="seo_desc" type="text" required="" placeholder="SEO Description">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" value="{{$item->seo_key}}" title="SEO Keywords" name="seo_key" type="text" required="" placeholder="SEO Keywords">
                </div>
                <div class="flex flex-no-wrap mt-3">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" value="{{$item->tech}}" title="Технологии" name="tech" type="text" required="" placeholder="Технологии">
                </div>

              </div>

              <div class="w-full p-10 bg-white mt-4">
                <div class="mt-2 flex flex-wrap items-center">
                  <div class="w-full">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 my-2" value="{{$item->text}}" type="text" name="text" placeholder="Описание главного изображения">
                  </div>
                  <input type="file" class="bg-white text-black p-3 w-1/2" name="main_img" id="imgSrcUpload">
                  <input type="hidden" name="currentSrc" value="{{$item->main_img}}">   
                  <div class="w-full">
                    <img src="/{{$item->main_img}}" alt="">  
                  </div>   
                </div>
              </div>
              
              {{-- Only VIEW --}}
              @foreach (json_decode($item->images, true) as $it)
                <div class="option-image-{{$loop->index}} w-full px-10 py-4 bg-white mt-4">
                  <div class="mt-2 w-full flex flex-wrap items-center text-black justify-center">
                    <input type="hidden" name="{{$loop->index}}-src"> 
                    <div class="block" id="{{$loop->index}}-full">
                      <div class="w-full">
                        <input readonly class="w-full px-5 py-1 text-gray-700 bg-gray-200 my-2" value="{{$it['capture']}}" type="text" name="{{$loop->index}}-caption" placeholder="Описание изображения">
                      </div>
                      <div class="w-full 1-prev">
                        <img src="/{{$it['img_path']}}" class="w-full h-auto" alt="">
                      </div>
                    </div>
                  </div>
                </div>                  
              @endforeach

              

              {{-- <div id="editor"></div> --}}
              
              
            </form>
          </div>

          


    </div>
</div>
@endsection
@section('js')
    
{{-- <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script> --}}
{{-- <script src="{{ asset('ckeditor/ckeditor.js') }}"></script> --}}
{{-- <script src="{{ asset('js/jq_tailwind_checkbox.js') }}"></script> --}}
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.js"></script> --}}


<script>

  window.onload = function () {
    // First event
    $('.option-image-1 input[name="1-image"]').on('change', function () {
      ajaxFunc(1);
      $('#1-full').removeClass('hidden'); //Show full info - image and input capture
      $('.option-image-2').removeClass('hidden'); //Show 2
      // Two event
      $('.option-image-2 input[name="2-image"]').on('change', function () {
        ajaxFunc(2);
        $('#2-full').removeClass('hidden'); //Show full info - image and input capture
        $('.option-image-3').removeClass('hidden'); //Show 2
        // Three event
        $('.option-image-3 input[name="3-image"]').on('change', function () {
          ajaxFunc(3);
          $('#3-full').removeClass('hidden'); //Show full info - image and input capture
        });
      });

    });

  }

  function ajaxFunc(number) {
    var file_data = $('input[name="'+number+'-image"]').prop('files')[0];
    var form_data = new FormData();
    form_data.append('file', file_data);
    $.ajax({
      type: "POST",
      url: "{{ route('notez.imageTempStore') }}",
      processData: false,
      cache: false,
      contentType: false,
      data: form_data,
      headers: {
          'X-CSRF-TOKEN': "{{ csrf_token() }}"
      },
      success: function (data) {
          // console.log('Ok');
          // console.log(data) 
          $('.'+number+'-prev').html(data['crop_block']);
          $('input[name="'+number+'-src"]').val(data['crop_base64']);         
      }
  });
  }  
</script>

@endsection