routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::domain('promo.devrules.ru')->group(function () {
    Route::get('/', function (){
        return 'bla bla bla';
    });
});
Route::domain('devrules.ru')->group(function () {
    Route::view('/', 'frontend.index')->name('home');

    Route::post('sendMessageToTelegram', 'SendToTelegramController');

    Route::get('notes', 'NotesController@indexFront')->name('notes');
    Route::get('notes/{note}', 'NotesController@showFront')->name('note.page');

    Route::get('myportfolio', 'PortfolioController@indexFront')->name('portfolio.front');
    Route::get('myportfolio/{item}', 'PortfolioController@showFront')->name('portfolio.page');

    Route::get('projects', 'ProjectsController@indexFront')->name('projects');
    Route::get('projects/{project}', 'ProjectsController@showFront')->name('project.page');

    Route::resource('notez', 'NotesController')->middleware('role:admin');
    Route::post('notez/image', 'NotesController@imageTempStore')->name('notez.imageTempStore');
    Route::post('notez/imageSave', 'NotesController@imageStore')->name('notez.imageSave');

    Route::resource('portfolioz', 'PortfolioController')->middleware('role:admin');

    Route::resource('projectes', 'ProjectsController')->middleware('role:admin');

    Auth::routes();
});

resources/views/frontend/layouts/admin_nav.blade.php
 {{-- Logout form panel --}}
 @if (isset(Auth::user()->name))
 {{-- Left buttons --}}
 @if (Request::is(['notez/*', 'portfolioz/*', 'projectes/*']))
 <div class="absolute  text-gray-700 z-20" style="top: 5rem; left: 10.5rem" >
    <div class="flex flex-row justify-center">
      @if (Request::is(['notez/*']))
        <a href="{{ route('notez.index') }}" class="flex items-center bg-white py-2 px-8 hover:bg-gray-300">
          Назад
        </a>          
      @endif
      @if (Request::is(['portfolioz/*']))
        <a href="{{ route('portfolioz.index') }}" class="flex items-center bg-white py-2 px-8 hover:bg-gray-300">
          Назад
        </a>          
      @endif
      @if (Request::is(['projectes/*']))
        <a href="{{ route('projectes.index') }}" class="flex items-center bg-white py-2 px-8 hover:bg-gray-300">
          Назад
        </a>          
      @endif
    </div>
 </div>
     
 @endif

 {{-- Right buttons --}}
 <div class="absolute  text-gray-700 z-20" style="top: 5rem; right: 8.5rem" >
     <div class="flex flex-row justify-center">
         <div class="flex flex-no-wrap items-center bg-white py-2 px-3 mr-2">
             <img class="flex h-8 w-8 rounded-full mr-2" src="/img/profile-img.jpeg" alt="">
             <p class="flex">{{ Auth::user()->name }}</p>
         </div>

        @if (Request::is(['notes', 'notez']))
          <div class="flex flex-no-wrap items-center bg-white  mr-2 hover:bg-gray-300">
            <a href="{{ route('notez.create') }}" class="flex py-4 px-3"><i class="fas fa-plus"></i></a>
          </div>            
          <div class="flex flex-no-wrap items-center bg-white  mr-2 hover:bg-gray-300">
            <a href="{{ route('notez.index') }}" class="flex py-4 px-3"><i class="fas fa-list"></i></a>
          </div>            
        @endif

        @if (Request::is(['myportfolio', 'portfolioz']))
          <div class="flex flex-no-wrap items-center bg-white mr-2 hover:bg-gray-300">
            <a href="{{ route('portfolioz.create') }}" class="flex py-4 px-3"><i class="fas fa-plus"></i></a>
          </div>            
          <div class="flex flex-no-wrap items-center bg-white mr-2 hover:bg-gray-300">
            <a href="{{ route('portfolioz.index') }}" class="flex py-4 px-3"><i class="fas fa-list"></i></a>
          </div>            
        @endif
        
        @if (Request::is(['projects', 'projectes']))
          <div class="flex flex-no-wrap items-center bg-white mr-2 hover:bg-gray-300">
            <a href="{{ route('projectes.create') }}" class="flex py-4 px-3"><i class="fas fa-plus"></i></a>
          </div>            
          <div class="flex flex-no-wrap items-center bg-white mr-2 hover:bg-gray-300">
            <a href="{{ route('projectes.index') }}" class="flex py-4 px-3"><i class="fas fa-list"></i></a>
          </div>            
        @endif
        {{-- <div class="flex mr-2">
             <div class="group inline-block">
                 <button
                   class="outline-none focus:outline-none px-3 py-3 bg-white flex items-center min-w-32"
                 >
                   <span class="pr-1 font-semibold flex-1">RBAC</span>
                   <span>
                     <svg
                       class="fill-current h-4 w-4 transform group-hover:-rotate-180
                       transition duration-150 ease-in-out"
                       xmlns="http://www.w3.org/2000/svg"
                       viewBox="0 0 20 20"
                     >
                       <path
                         d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"
                       />
                     </svg>
                   </span>
                 </button> --}}
                 {{-- <ul --}}
                   {{-- class="bg-white border rounded-sm transform scale-0 group-hover:scale-100 absolute 
                         transition duration-150 ease-in-out origin-top min-w-32"> --}}
                     {{-- <li class="px-2 py-2 hover:bg-gray-200">
                         <a href="{{route('users.index')}}">Users</a>
                     </li> --}}
                     {{-- <li class="px-3 py-2 hover:bg-gray-200">
                         <a href="{{route('roles.index')}}">Roles</a>
                     </li>
                     <li class="px-3 py-2 hover:bg-gray-200">
                         <a href="{{route('permission.index')}}">Permission</a>
                     </li> --}}
                   
                 {{-- </ul> --}}
               {{-- </div>
               
               <style>
                 /* since nested groupes are not supported we have to use 
                    regular css for the nested dropdowns 
                 */
                 li>ul                 { transform: translatex(100%) scale(0) }
                 li:hover>ul           { transform: translatex(101%) scale(1) }
                 li > button svg       { transform: rotate(-90deg) }
                 li:hover > button svg { transform: rotate(-270deg) }
               
                 .group:hover .group-hover\:scale-100 { transform: scale(1) }
                 .group:hover .group-hover\:-rotate-180 { transform: rotate(180deg) }
                 .scale-0 { transform: scale(0) }
                 .min-w-32 { min-width: 8rem }
               </style>
         </div> --}}

        <div class="flex flex-no-wrap items-center bg-white">
             <a class="flex py-4 px-3 hover:bg-gray-300" 
                 href="{{ route('logout') }}"
                 title="Выход"
                 onclick="event.preventDefault();
                 document.getElementById('logout-form').submit();">
                 <i class="fas fa-power-off"></i>
             </a>

             <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                 @csrf
             </form>
        </div>
     </div>
     
 </div>            
@endif

resources/views/frontend/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Page</title>
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet">
</head>
<body  class="leading-normal tracking-normal text-white gradient" style="font-family: 'Raleway', sans-serif;">
    
    @yield('content')
   
</body>
</html>

resources/views/frontend/layouts/footer.blade.php
<!--Footer-->
<footer class="bg-white">
	<div class="container mx-auto  px-8">

        <div class="w-full flex flex-wrap pt-4 items-center justify-center">
			<a class="w-full text-gray-500 no-underline hover:no-underline font-bold text-2xl lg:text-2xl flex items-center justify-center"  href="{{ route('home') }}"> 
                <i class="text-xl md:text-3xl mr-2 fas fa-laptop-code"></i> DEV.RULES
            </a>
            <p class="w-full text-gray-500 flex text-xl justify-center">sefkiss.torn@yandex.ru</p>
            <p class="w-full text-gray-500 flex text-sm justify-center">&copy Все права защищены {{date('Y')}}</p>		         
            
        </div>
    </div>
	
	<a href="https://www.freepik.com/free-photos-vectors/background" class="bg-transparent text-gray-300 font-light">Background vector created by freepik - www.freepik.com</a>

</footer>

resources/views/frontend/layouts/main.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@isset($title){{$title}} | @endisset DEV.RULES</title>

    <meta name="author" content="Svjatoslav Torn">
    <meta name="description" content="@isset($description){{$description}}@endisset">
    <meta name="keywords" content="@isset($keywords){{$keywords}}@endisset">

    @if(env('APP_ENV') == 'production')
        <meta name="yandex-verification" content="d11c326f6e78d0e3" />
        <!-- Yandex.Metrika counter --> <script type="text/javascript" > (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(62517976, "init", { clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); </script> <noscript><div><img src="https://mc.yandex.ru/watch/62517976" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
    @endif
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link href="/hljs/styles/monokai-sublime.css" rel="stylesheet" />
    {{-- <link href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.20.0/themes/prism-okaidia.min.css" rel="stylesheet" /> --}}
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;600;700;800;900&display=swap" rel="stylesheet">
</head>
<body  class="leading-normal tracking-normal text-white gradient" style="font-family: 'Nutino', sans-serif;">
    
    @include('frontend.layouts.navigation')
    @include('frontend.layouts.admin_nav')
    @yield('content')
    @include('frontend.layouts.footer')
    {{-- <span class="hidden sm:bg-white" id="navMobFix"></span> --}}
    <script src="/js/jquery.js"></script>
    <script src="/js/app.js"></script>
    <script src="/js/main.js"></script>
    {{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"></script> --}}
    <script src="/hljs/highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    @yield('js')
</body>
</html>

resources/views/frontend/layouts/navigation.blade.php
<!--Nav-->
<nav id="header" class="fixed w-full z-30 top-0 text-white">

	<div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-2">
			
		<div class="pl-4 flex items-center">
			<a class="toggleColour text-white no-underline hover:no-underline font-bold text-2xl lg:text-4xl flex items-center"  href="{{ route('home') }}">
				<i class="text-xl md:text-3xl mr-2 fas fa-laptop-code"></i> DEV.RULES
			</a>
		</div>

		<div class="block lg:hidden pr-4">
			<button id="nav-toggle" class="flex items-center p-1 text-orange-800 hover:text-gray-900">
				<svg class="fill-current h-6 w-6" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
			</button>
		</div>

		<div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-white lg:bg-transparent text-black p-4 lg:p-0 z-20" id="nav-content">
			{{-- <div class="flex-1 w-full mx-auto max-w-sm content-center py-4 lg:py-0">
				<div class="relative pull-right pl-4 pr-4 md:pr-0">
				   <input type="search" placeholder="Search" class="w-full bg-gray-100 text-sm text-gray-800 transition border focus:outline-none focus:border-purple-500 rounded py-1 px-2 pl-10 appearance-none leading-normal">
				   <div class="absolute search-icon" style="top: 0.375rem;left: 1.75rem;">
					  <svg class="fill-current pointer-events-none text-gray-800 w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
						 <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
					  </svg>
				   </div>
				</div>
			 </div> --}}
			<ul class="list-reset lg:flex justify-end flex-1 items-center">
				
				<li class="mr-3 text-center">
					<a class="{{ Request::is('home') ? 'bg-gray-200 cursor-default' : 'hover:text-gray-700 hover:text-underline'}} clickk inline-block text-white font-bold  no-underline py-4 md:-my-4 md:py-6 px-6" 
						href="{{ route('home') }}">
						Главная</a>
				</li>
				<li class="mr-3 text-center">
					<a class="{{ Request::is(['projects', 'projects/*']) ? 'bg-gray-200 cursor-default' : 'hover:text-gray-700 hover:text-underline'}} clickk inline-block text-white font-bold  no-underline py-4 md:-my-4 md:py-6 px-6" 
						href="{{ route('projects') }}">
						Проекты</a>
				</li>
				<li class="mr-3 text-center">
					<a class="{{ Request::is(['myportfolio', 'myportfolio/*']) ? 'bg-gray-200 cursor-default' : 'hover:text-gray-700 hover:text-underline'}} clickk inline-block text-white font-bold  no-underline py-4 md:-my-4 md:py-6 px-6" 
						href="{{ route('portfolio.front') }}">
						Портфолио</a>
				</li>
				<li class="mr-3 text-center">
					<a class="{{ Request::is(['notes', 'notes/*']) ? 'bg-gray-200 cursor-default' : 'hover:text-gray-700 hover:text-underline'}} clickk inline-block text-white font-bold  no-underline py-4 md:-my-4 md:py-6 px-6" 
						href="{{ route('notes') }}">
						Заметки</a>
				</li>
				
			</ul>
		</div>
	</div>
	
	<hr class="border-b border-gray-100 opacity-25 my-0 py-0" />
</nav>