routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::domain('promo.devrules.ru')->group(function () {
    Route::get('/', function (){
        return 'bla bla bla';
    });
});
Route::domain('devrules.ru')->group(function () {
    Route::view('/', 'frontend.index')->name('home');

    Route::post('sendMessageToTelegram', 'SendToTelegramController');

    Route::get('notes', 'NotesController@indexFront')->name('notes');
    Route::get('notes/{note}', 'NotesController@showFront')->name('note.page');

    Route::get('myportfolio', 'PortfolioController@indexFront')->name('portfolio.front');
    Route::get('myportfolio/{item}', 'PortfolioController@showFront')->name('portfolio.page');

    Route::get('projects', 'ProjectsController@indexFront')->name('projects');
    Route::get('projects/{project}', 'ProjectsController@showFront')->name('project.page');

    Route::resource('notez', 'NotesController')->middleware('role:admin');
    Route::post('notez/image', 'NotesController@imageTempStore')->name('notez.imageTempStore');
    Route::post('notez/imageSave', 'NotesController@imageStore')->name('notez.imageSave');

    Route::resource('portfolioz', 'PortfolioController')->middleware('role:admin');

    Route::resource('projectes', 'ProjectsController')->middleware('role:admin');

    Auth::routes();
});

app/Notes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notes extends Model{
    // 

    public $fillable = [
        'title', 'content', 'seo_desc', 'seo_key', 'img_src', 'slug', 'user_id', 'status', 'preview', 'read_time', 'main_tag'
    ];

    // public function registerMediaCollections()
    // {
    //     $this->addMediaCollection('img_src');
    // }

    // public function registerMediaConversions(Media $media = null)
    // {
    //     $this->addMediaConversion('detail_hd')
    //         ->width(1920)
    //         ->height(1080)
    //         ->performOnCollections('gallery');
    // }
}

app/Http/Controllers/NotesController.php
<?php

namespace App\Http\Controllers;

use App\Notes;
use Illuminate\Http\Request;
// use Illuminate\Support\Facades\Input;
// use Illuminate\Http\UploadedFile;

class NotesController extends Controller
{

    /**
     * Display a listing of the resource for frontend.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexFront()
    {
//        var_dump(\Auth::user()->hasRole('admin'));die;

        return view('frontend.notes', [
            'notes' => Notes::
                orderBy('created_at', 'desc')
                ->where(['status' => true])
                ->get()
                ->take(7),
        ]);
    }

    public function showFront($slug)
    {
        // setlocale(LC_TIME, 'ru');
        // \Carbon\Carbon::setLocale('ru');
        // var_dump(Notes::inRandomOrder()->limit(2)->get());die;
        // $note = Notes::find($id);
        $note = Notes::where(['slug' => $slug])->first();
        // var_dump(strftime('%e %B, %Y', strtotime($note->created_at)));die;
        $note->increment('view_counter');
        return view('frontend.page._note_page', [
            'note' => $note,
            'relatedNotes' => Notes::inRandomOrder()->limit(2)->get(),
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notes = Notes::orderBy('id', 'desc')->get();
        return view('control.notes._note_list', [
            'notes' => $notes,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('control.notes._create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->img_src){
            $data = explode(',', $request->img_src);
            $img = base64_decode($data[1]);
            $path = 'posts/'.\Str::random(30).'.jpeg';
            file_put_contents($path, $img);
        }else{
            $path = null;
        }

        Notes::create([
            'user_id' => \Auth::user()->id,
            'title' => $request->get('title'),
            'read_time' => $request->input('read_time'),
            'main_tag' => $request->input('main_tag'),
            'img_src' => $path,
            'slug' => \Str::slug($request->get('title')),
            'seo_desc' => $request->get('seo_desc'),
            'preview' => $request->input('preview'),
            'seo_key' => $request->get('seo_key'),
            'content' => $request->get('content'),
            'status' => $request->get('status') == null ? 0 : 1,            
        ]);

        return redirect()->route('notez.index');
    }

    public function imageTempStore(Request $request)
    {
        $base64 = 'data:image/'.$request->file('file')->extension().';base64,' . base64_encode(file_get_contents($request->file('file')->path()));
        return [
            'crop_block' => '<img class="w-full h-auto" id="image" src="'.$base64.'" alt="image">',
            'crop_base64' => $base64,
        ];
    }

    // Ajax method
    // request - image from CKEditor
    // return SRC for uploaded image
    public function imageStore(Request $request)
    {
        // var_dump($request->get('CKEditorFuncNum'));die;

        $CKEditor = $request->input('CKEditor');
        $funcNum  = $request->input('CKEditorFuncNum');
        $message  = $url = '';
        // var_dump($funcNum);die;
        if ($request->hasFile('upload')) {
            // var_dump('Yeas');die;
            $file = $request->file('upload');
            if ($file->isValid()) {
                // $filename =rand(1000,9999).$file->getClientOriginalName();
                // $file->move(public_path().'/wysiwyg/', $filename);
                // $url = url('wysiwyg/' . $filename);
                
                $filename = \Str::random(15).$file->getClientOriginalName();
                $url = url('wysiwyg/' . $filename);
                $imageIm = \Image::make($file);
                if($imageIm->width() > 1921){
                    $imageIm->resize(1920, null, function ($constraint) {
                        $constraint->aspectRatio();
                    });
                }
                $imageIm->save(\public_path().'/wysiwyg/'.$filename, 80, 'jpg');
//                ->insert('img/water.png', 'bottom-left', 25, 0)
                
            } else {
                $message = 'An error occurred while uploading the file.';
            }
        } else {
            // var_dump('No');die;
            $message = 'No file uploaded.';
        }
        return '<script>window.parent.CKEDITOR.tools.callFunction('.$funcNum.', "'.$url.'", "'.$message.'")</script>';
    }

 /**
     * Display the specified resource.
     *
     * @param  \App\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function show(Notes $notes)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Notes  $notes
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // \var_dump($id);die;
        $note = Notes::find($id);
        // \var_dump($note->toArray());die;
        return view('control.notes._update_note', [
            'note' => $note,
            'ref' => \Request::server('HTTP_REFERER'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Notes  $notes
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        if (strlen($request->get('img_src')) > 100 ) {
            $data = explode(',', $request->img_src);
            $img = base64_decode($data[1]);
            $path = 'posts/'.\Str::random(30).'.jpeg';
            file_put_contents($path, $img);
        }else{
            $path = $request->get('img_src');
        }
// var_dump($id);die;
        Notes::find($id)->update([
            'title' => $request->get('title'),            
            'read_time' => $request->input('read_time'),
            'main_tag' => $request->input('main_tag'),
            'preview' => $request->input('preview'),
            'img_src' => $path,
            'slug' => \Str::slug($request->get('title')),
            'seo_desc' => $request->get('seo_desc'),
            'seo_key' => $request->get('seo_key'),
            'content' => $request->get('content'),
            'status' => $request->get('status') == null ? 0 : 1,
        ]);
        // Toastr::success('Сток успешно отредактирован', 'Йууухуууу');

        if(\Str::contains($request->input('refLink'), 'notes/')){
            return redirect()->route('note.page', \Str::afterLast($request->input('refLink'), '/'));
        }

        return redirect()->route('notez.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Notes  $notes
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $note = Notes::find($id);

        if(file_exists($note->img_src)) unlink($note->img_src);

        \preg_match_all('/wysiwyg.([a-z0-9_\.-]+)/', $note->content, $m, PREG_SET_ORDER, 0);
        foreach ($m as $value) {
            if(\file_exists($value[0])) \unlink($value[0]);
        }

        $note->delete();

        return redirect()->route('notez.index');

    }
}

resources/views/control/notes/_create.blade.php
@extends('frontend.layouts.main')

@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.css">
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>
<span id="navFix" class="hidden"></span>
<!--Hero-->
<div class="pt-6 md:pt-32">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
      
    
        <div class="w-full leading-loose mb-3">
            <form id="createNoteForm" class="w-full m-4 "  action="{{ route('notez.store') }}" method="POST" enctype="multipart/form-data">
              {!! csrf_field() !!}
              <div class="w-full p-10 bg-white">
                <p class="text-gray-800 font-medium text-xl">Создание новой заметки:</p>
                <div class="mt-4">
                  <button class="px-4 w-full hover:bg-blue-600 py-1 text-white font-light tracking-wider bg-blue-500 rounded" type="submit">Добавить</button>
                </div>
                <div class="flex flex-no-wrap py-2 text-black">
                  <label for="statusToggle" class="mr-2">Опубликовать: </label><input class="px-3 border-double border-2 border-blue-600 text-white whitespace-no-wrap overflow-hidden w-8 h-8" type="checkbox" id="statusToggle" name="status" />
                  
                </div>
                <div class="flex flex-no-wrap">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" title="Заголовок" name="title" type="text" required="" placeholder="Заголовок">
                </div>
                <div class="flex flex-no-wrap mt-2">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" title="Текст для карточки" name="preview" type="text" required="" placeholder="Текст для карточки">
                </div>
                <div class="mt-2 flex flex-no-wrap items-center">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2" title="Основной тег заметки" name="main_tag" type="text" required="" placeholder="Основной тег заметки">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" title="Время чтения заметки" name="read_time" type="number" required="" placeholder="Время чтения">
                </div>
                <div class="mt-2 flex flex-no-wrap items-center">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2" title="SEO Description" name="seo_desc" type="text" required="" placeholder="SEO Description">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" title="SEO Keywords" name="seo_key" type="text" required="" placeholder="SEO Keywords">
                </div>

              </div>
              <div class="w-full p-10 bg-white mt-4">
                <div class="mt-2 flex flex-wrap items-center">
                  <span id="cutImage" class="text-center bg-white text-white bg-green-500 hover:bg-green-600 cursor-pointer p-2 border w-1/2">Обрезать изображение</span>
                  <input type="hidden" name="img_src" value="" id="src">
                  <input type="file" class="bg-white text-black p-3 w-1/2" name="upload" id="imgSrcUpload">
                  
                  <div class="w-1/2 " id="originalImage">
                  </div>
                  <div class="w-1/2 pl-2" id="cropperImage">
  
                  </div>
                </div>
              </div>
              
              <div class="w-full p-10 bg-white mt-4">
                <div class="mt-2 w-full flex flex-no-wrap items-center text-black px-16">
                  <textarea name="content" id="editor"  width="100%" class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2"></textarea>
                </div>

              </div>

              {{-- <div id="editor"></div> --}}
              
              
            </form>
          </div>

          


    </div>
</div>
@endsection
@section('js')
    
{{-- <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script> --}}
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
{{-- <script src="{{ asset('js/jq_tailwind_checkbox.js') }}"></script> --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.js"></script>
<script>
  CKEDITOR.replace( 'editor', {
        filebrowserUploadUrl: "{{route('notez.imageSave', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form'
    });
   CKEDITOR.config.width = '100%';
   CKEDITOR.config.height = '100vh';
  //  CKEDITOR.replace('editor', {
  //       filebrowserUploadUrl: "",
  //       // filebrowserUploadMethod: 'form'
  //   });
</script>

<script>
  $('#imgSrcUpload').on('change', function () {
    var file_data = $('#imgSrcUpload').prop('files')[0];
    var form_data = new FormData();
    form_data.append('file', file_data);
          $.ajax({
            type: "POST",
            url: "{{ route('notez.imageTempStore') }}",
            processData: false,
            cache: false,
            contentType: false,
            data: form_data,
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            },
            success: function (data) {
                console.log(data);
                $('#originalImage').html(data['crop_block']);
                cropperInit();
            }
        });
  });

  function cropperInit(){
    const image = document.getElementById('image');
    const cropper = new Cropper(image, {
      aspectRatio: 16 / 9,
      scalable: false,
      zoomable: false,
    });

    $('#cutImage').on('click', function(){
      cropper.getCroppedCanvas({
        width: 1920,
        height: 1080,
        fillColor: '#fff',
        imageSmoothingEnabled: false,
        imageSmoothingQuality: 'medium',
      });
      cropper.getCroppedCanvas().toBlob((blob) => {
        const formData = new FormData();
      formData.append('file', blob);
      $.ajax({
            type: "POST",
            url: "{{ route('notez.imageTempStore') }}",
            processData: false,
            cache: false,
            contentType: false,
            data: formData,
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            },
            success: function (data) {
                console.log(data);
                $('#cropperImage').html(data['crop_block']);
                $('#src').val(data['crop_base64']);
            }
        });
      });
    });
  }
</script>

<script>
  // import Cropper from 'cropperjs';

// const image = document.getElementById('image');
// const cropper = new Cropper(image, {
//   aspectRatio: 16 / 9,
//   crop(event) {
//     console.log(event.detail.x);
//     console.log(event.detail.y);
//     console.log(event.detail.width);
//     console.log(event.detail.height);
//     console.log(event.detail.rotate);
//     console.log(event.detail.scaleX);
//     console.log(event.detail.scaleY);
//   },
// });
</script>
@endsection

resources/views/control/notes/_note_list.blade.php
@extends('frontend.layouts.main')

@section('content')
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>


<span id="navFix" class="hidden"></span>
<!--Hero-->
<div class="pt-6 md:pt-32 pb-8 h-full">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">

        <table class="border-collapse w-full mt-4">
            <thead>
                <tr>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Дата</th>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Просмотры</th>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell w-3/5">Заголовок</th>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Статус</th>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($notes as $note)
                <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                        {{\Carbon\Carbon::parse($note['created_at'])->format('d.m.Y')}}
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                        {{$note->view_counter}}
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                        {{$note->title}}
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                    <span class="rounded {{$note->status ? 'bg-green-400' : 'bg-red-400'}}  py-1 px-3 text-xs font-bold">{{$note->status ? 'Опубликовано' : 'Черновик'}}</span>
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                        <form action="{{ route('notez.destroy', $note->id) }}" method="POST">
                            @csrf
                            @method('DELETE')       
                            <a href="{{route('notez.edit', $note->id)}}" class="text-green-400 hover:text-blue-600 underline" title="Редактировать"><i class="far fa-edit"></i></a>
                            <button type="submit" class="text-red-400 hover:text-blue-600 underline pl-6" title="Удалить заметку"><i class="far fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
                    
                @endforeach
                
            </tbody>
        </table>

    </div>
</div>

@endsection

resources/views/control/notes/_update_note.blade.php
@extends('frontend.layouts.main')

@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.css">
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>
<span id="navFix" class="hidden"></span>
<!--Hero-->
<div class="pt-6 md:pt-32">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
      
    
        <div class="w-full leading-loose mb-3">
          <form id="createNoteForm" class="w-full m-4"  action="{{ route('notez.update', $note->id) }}" method="POST" enctype="multipart/form-data">
            {!! csrf_field() !!}
            @method('PUT')
            <input type="hidden" name="refLink" value="{{$ref}}">
            <div class="w-full p-10 bg-white shadow-lg">
                <p class="text-gray-800 font-medium text-xl">Редактирование заметки: <span class="font-bold">{{$note->title}}</span></p>
                <div class="mt-4">
                  <button class="px-4 w-full py-1 text-white font-light tracking-wider hover:bg-blue-600 bg-blue-500 rounded" type="submit">Обновить</button>
                </div>
                <div class="flex flex-no-wrap py-2 text-black">
                  <label for="statusToggle" class="mr-2">Опубликовать: </label><input class="px-3 border-double border-2 border-blue-600 text-white whitespace-no-wrap overflow-hidden w-8 h-8" type="checkbox" id="statusToggle" name="status"  {{ $note->status ? 'checked' : '' }}/>
                </div>
                <div class="flex flex-no-wrap">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" value="{{$note->title}}" title="Заколовок заметки" name="title" type="text" required="" placeholder="Заголовок">
                </div>
                <div class="flex flex-no-wrap mt-2">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" value="{{$note->preview}}" title="Текст для карточки заметки" name="preview" type="text" required="" placeholder="Текст для карточки заметки">
                </div>
                <div class="mt-2 flex flex-no-wrap items-center">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2" value="{{$note->main_tag}}" title="Основной тег заметки" name="main_tag" type="text" required="" placeholder="Основной тег заметки">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" value="{{$note->read_time}}" title="Время на чтение заметки" name="read_time" type="number" required="" placeholder="Время чтения">
                </div>
                <div class="mt-2 flex flex-no-wrap items-center">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2" value="{{$note->seo_desc}}" title="SEO Description" name="seo_desc" type="text" required="" placeholder="SEO Description">
                  <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded" value="{{$note->seo_key}}" title="SEO Keywords" name="seo_key" type="text" required="" placeholder="SEO Keywords">
                </div>
            </div>

            <div class="w-full p-10 bg-white shadow-lg mt-4">
              <div class="mt-2 flex flex-wrap items-center">
                <span id="cutImage" class="text-center bg-white text-white bg-green-500 hover:bg-green-600 cursor-pointer p-2 border w-1/2">Обрезать изображение</span>
                <input type="hidden" name="img_src" value="{{$note->img_src}}" id="src">
                <input type="file" class="bg-white text-black p-3 w-1/2" name="upload" id="imgSrcUpload">
                
                <div class="w-1/2 " id="originalImage">
                </div>
                <div class="w-1/2 pl-2" id="cropperImage">
                    <img src="/{{$note->img_src}}" alt="Current image">
                </div>
              </div>
            </div>
            
            <div class="w-full shadow-lg mt-4">
              <div class="mt-2 w-full flex flex-no-wrap items-center text-black">
                  <textarea name="content" id="editor"  width="100%" class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2">{{$note->content}}</textarea>
                </div>
            </div>
              
            </form>
          </div>

          


    </div>
</div>
@endsection
@section('js')
    
{{-- <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script> --}}
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
{{-- <script src="{{ asset('js/jq_tailwind_checkbox.js') }}"></script> --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.js"></script>
<script>
  CKEDITOR.replace( 'editor', {
        filebrowserUploadUrl: "{{route('notez.imageSave', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form'
    });
   CKEDITOR.config.width = '100%';
   CKEDITOR.config.height = '100vh';
  //  CKEDITOR.replace('editor', {
  //       filebrowserUploadUrl: "",
  //       // filebrowserUploadMethod: 'form'
  //   });
</script>

<script>
  $('#imgSrcUpload').on('change', function () {
    var file_data = $('#imgSrcUpload').prop('files')[0];
    var form_data = new FormData();
    form_data.append('file', file_data);
          $.ajax({
            type: "POST",
            url: "{{ route('notez.imageTempStore') }}",
            processData: false,
            cache: false,
            contentType: false,
            data: form_data,
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            },
            success: function (data) {
                console.log(data);
                $('#originalImage').html(data['crop_block']);
                cropperInit();
            }
        });
  });

  function cropperInit(){
    const image = document.getElementById('image');
    const cropper = new Cropper(image, {
      aspectRatio: 16 / 9,
      scalable: false,
      zoomable: false,
    });

    $('#cutImage').on('click', function(){
      cropper.getCroppedCanvas({
        width: 1920,
        height: 1080,
        fillColor: '#fff',
        imageSmoothingEnabled: false,
        imageSmoothingQuality: 'medium',
      });
      cropper.getCroppedCanvas().toBlob((blob) => {
        const formData = new FormData();
      formData.append('file', blob);
      $.ajax({
            type: "POST",
            url: "{{ route('notez.imageTempStore') }}",
            processData: false,
            cache: false,
            contentType: false,
            data: formData,
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            },
            success: function (data) {
                console.log(data);
                $('#cropperImage').html(data['crop_block']);
                $('#src').val(data['crop_base64']);
            }
        });
      });
    });
  }
</script>

<script>
  // import Cropper from 'cropperjs';

// const image = document.getElementById('image');
// const cropper = new Cropper(image, {
//   aspectRatio: 16 / 9,
//   crop(event) {
//     console.log(event.detail.x);
//     console.log(event.detail.y);
//     console.log(event.detail.width);
//     console.log(event.detail.height);
//     console.log(event.detail.rotate);
//     console.log(event.detail.scaleX);
//     console.log(event.detail.scaleY);
//   },
// });
</script>
@endsection