routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::domain('promo.devrules.ru')->group(function () {
    Route::get('/', function (){
        return 'bla bla bla';
    });
});
Route::domain('devrules.ru')->group(function () {
    Route::view('/', 'frontend.index')->name('home');

    Route::post('sendMessageToTelegram', 'SendToTelegramController');

    Route::get('notes', 'NotesController@indexFront')->name('notes');
    Route::get('notes/{note}', 'NotesController@showFront')->name('note.page');

    Route::get('myportfolio', 'PortfolioController@indexFront')->name('portfolio.front');
    Route::get('myportfolio/{item}', 'PortfolioController@showFront')->name('portfolio.page');

    Route::get('projects', 'ProjectsController@indexFront')->name('projects');
    Route::get('projects/{project}', 'ProjectsController@showFront')->name('project.page');

    Route::resource('notez', 'NotesController')->middleware('role:admin');
    Route::post('notez/image', 'NotesController@imageTempStore')->name('notez.imageTempStore');
    Route::post('notez/imageSave', 'NotesController@imageStore')->name('notez.imageSave');

    Route::resource('portfolioz', 'PortfolioController')->middleware('role:admin');

    Route::resource('projectes', 'ProjectsController')->middleware('role:admin');

    Auth::routes();
});

app/Projects.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Projects extends Model
{
    public $fillable = [
        'name', 'slug', 'tech', 'description', 'main_img', 'content',
    ];
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Projects;
use Illuminate\Http\Request;

class ProjectsController extends Controller
{

    /**
     * Display a listing of the resource for frontend.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexFront()
    {
        $projects = Projects::orderBy('created_at', 'desc')->get()->take(9);

        return view('frontend.projects', [
            'projects' => $projects,
        ]);
    }

    public function showFront($slug)
    {
        return view('frontend.page._project_page', [
            'project' => Projects::where(['slug' => $slug])->first(),
        ]);
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Projects::orderBy('created_at', 'desc')->get();

        return view('control.projects._list', [
            'projects' => $projects,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('control.projects._create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->file('main_img')->isValid()){
            // $path = $request->file('main_img')->store('portfolio');
            $path = 'portfolio/'.\Str::random(20).'.jpg';
            $img = \Image::make($request->file('main_img'))->save($path, 80, 'jpg');
        }

        Projects::create([
            'name' => $request->input('name'),
            'tech' => $request->input('tech'),
            'description' => $request->input('description'),
            'content' => $request->input('content'),
            'slug' => \Str::slug($request->input('name')),
            'main_img' => $path,           
        ]);

        return redirect()->route('projectes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Projects  $projects
     * @return \Illuminate\Http\Response
     */
    public function show(Projects $projects)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Projects  $projects
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // var_dump(\Str::afterLast(\Request::server('HTTP_REFERER'), '/'));die;
        return view('control.projects._update', [
            'project' => Projects::find($id),
            'ref' => \Request::server('HTTP_REFERER'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Projects  $projects
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->hasFile('main_img')){
            if($request->file('main_img')->isValid()){
                // $path = $request->file('main_img')->store('portfolio');
                $path = 'portfolio/'.\Str::random(20).'.jpg';
                $img = \Image::make($request->file('main_img'))->save($path, 80, 'jpg');
                unlink($request->input('currentSrc'));
            }
        }else{
            $path = $request->input('currentSrc');
        }
      
        Projects::find($id)
            ->update([
                'name' => $request->input('name'),
                'tech' => $request->input('tech'),
                'description' => $request->input('description'),
                'content' => $request->input('content'),
                'slug' => \Str::slug($request->input('name')),
                'main_img' => $path,
            ]);
       
        if(\Str::contains($request->input('refLink'), 'projects/')){
            return redirect()->route('project.page', \Str::afterLast($request->input('refLink'), '/'));
        }
        return redirect()->route('projectes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Projects  $projects
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Projects::find($id);
        if(unlink($project->main_img)){

            \preg_match_all('/wysiwyg.([a-z0-9_\.-]+)/', $project->content, $m, PREG_SET_ORDER, 0);
            foreach ($m as $value) {
                if(\file_exists($value[0])) \unlink($value[0]);
            }

            $project->delete();
        }
        return redirect()->route('projectes.index');
    }
}

resources/views/control/projects/_create.blade.php
@extends('frontend.layouts.main')

@section('content')
{{-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.css"> --}}
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>
<span id="navFix" class="hidden"></span>
<!--Hero-->
<div class="pt-6 md:pt-32">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
      
    
        <div class="w-full leading-loose mb-3 flex justify-center">
            <form id="createPortForm" class="w-3/4 m-4 "  action="{{ route('projectes.store') }}" method="POST" enctype="multipart/form-data">
              {!! csrf_field() !!}
              <div class="w-full p-10 bg-white">
                <p class="text-gray-800 font-medium text-xl">Добавление проекта:</p>
                <div class="flex mt-4 mb-3">
                  <button class="px-4 w-full hover:bg-blue-600 py-1 text-white font-light tracking-wider bg-blue-500 rounded" 
                          type="submit">Добавить</button>
                </div>               
                <div class="flex flex-no-wrap">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" title="Название проекта" name="name" type="text" required="" placeholder="Название проекта">
                </div>
                
                <div class="flex flex-no-wrap mt-3">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" title="Описание" name="description" type="text" required="" placeholder="Описание краткое">
                </div>
                
                <div class="flex flex-no-wrap mt-3">
                    <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" title="Технологии" name="tech" type="text" required="" placeholder="Технологии">
                </div>

              </div>

              <div class="w-full p-10 bg-white mt-4">
                <div class="mt-2 flex flex-wrap items-center">
                  <input required="" type="file" class="bg-white text-black p-3 w-1/2" name="main_img" id="imgSrcUpload">      
                </div>
              </div>
              
              <div class="w-full bg-white mt-4">
                <div class="mt-2 w-full flex flex-no-wrap items-center text-black ">
                  <textarea name="content" id="editor"  width="100%" class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2"></textarea>
                </div>
              </div>
              
              
            </form>
          </div>

          


    </div>
</div>
@endsection
@section('js')

<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

<script>
  CKEDITOR.replace( 'editor', {
        filebrowserUploadUrl: "{{route('notez.imageSave', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form'
    });
   CKEDITOR.config.width = '100%';
   CKEDITOR.config.height = '100vh';
</script>
@endsection

resources/views/control/projects/_list.blade.php
@extends('frontend.layouts.main')

@section('content')
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>


<span id="navFix" class="hidden"></span>
<!--Hero-->
<div class="pt-6 md:pt-32 pb-8 h-full">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">

        <table class="border-collapse w-full mt-4">
            <thead>
                <tr>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Дата</th>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell w-3/5">Название</th>
                    <th class="p-3 font-bold uppercase bg-gray-200 text-gray-600 border border-gray-300 hidden lg:table-cell"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($projects as $project)
                <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0">
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                        {{\Carbon\Carbon::parse($project['created_at'])->format('d.m.Y')}}
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                        {{$project->name}}
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                        <form action="{{ route('projectes.destroy', $project->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
       
                            <a href="{{route('projectes.edit', $project->id)}}" class="text-green-400 hover:text-blue-600 underline" title="Редактировать проект"><i class="far fa-edit"></i></a>
                            <button type="submit" class="text-red-400 hover:text-blue-600 underline pl-6" title="Удалить проект"><i class="far fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
                    
                @endforeach
                
            </tbody>
        </table>

    </div>
</div>

@endsection

resources/views/control/projects/_update.blade.php
@extends('frontend.layouts.main')

@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.min.css">
<style>
    .gradient{
        background: rgb(131,131,131);
        background: linear-gradient(90deg, rgba(131,131,131,1) 0%, rgba(209,209,209,0.7010154403558299) 36%, rgba(142,142,142,1) 100%);
    }
</style>
<span id="navFix" class="hidden"></span>



<div class="pt-6 md:pt-32">
    <div class="container px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
      
    
      <div class="w-full leading-loose mb-3 flex justify-center">
        <form id="createPortForm" class="w-3/4 m-4 "  action="{{ route('projectes.update', $project->id) }}" method="POST" enctype="multipart/form-data">
          {!! csrf_field() !!}
          @method('PUT')
          <input type="hidden" name="refLink" value="{{$ref}}">
          <div class="w-full p-10 bg-white">
            <p class="text-gray-800 font-medium text-xl">Обновление проекта:</p>
            <div class="flex mt-4 mb-3">
              <button class="px-4 w-full hover:bg-blue-600 py-1 text-white font-light tracking-wider bg-blue-500 rounded" 
                      type="submit">Обновить</button>
            </div>               
            <div class="flex flex-no-wrap">
                <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" value="{{$project->name}}" title="Название проекта" name="name" type="text" required="" placeholder="Название проекта">
            </div>
            
            <div class="flex flex-no-wrap mt-3">
                <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" value="{{$project->description}}" title="Описание проекта" name="description" type="text" required="" placeholder="Краткое описание проекта">
            </div>
            
            <div class="flex flex-no-wrap mt-3">
                <input class="w-full px-5 py-1 text-gray-700 bg-gray-200 mr-2" value="{{$project->tech}}" title="Технологии" name="tech" type="text" required="" placeholder="Технологии">
            </div>

          </div>

          <div class="w-full p-10 bg-white mt-4">
            <div class="mt-2 flex flex-wrap items-center">
              <input type="file" class="bg-white text-black p-3 w-1/2" name="main_img" id="imgSrcUpload">  
              <input type="hidden" name="currentSrc" value="{{$project->main_img}}"> 
              <div class="w-full">
                <img src="/{{$project->main_img}}" alt="">
              </div>   
            </div>
          </div>
          
          <div class="w-full bg-white mt-4">
            <div class="mt-2 w-full flex flex-no-wrap items-center text-black ">
              <textarea name="content" id="editor"  width="100%" class="w-full px-5 py-1 text-gray-700 bg-gray-200 rounded mr-2">{{$project->content}}</textarea>
            </div>
          </div>
          
          
        </form>
      </div>


    </div>
</div>
@endsection
@section('js')

<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

<script>
  CKEDITOR.replace( 'editor', {
        filebrowserUploadUrl: "{{route('notez.imageSave', ['_token' => csrf_token() ])}}",
        filebrowserUploadMethod: 'form'
    });
   CKEDITOR.config.width = '100%';
   CKEDITOR.config.height = '100vh';
</script>
@endsection